FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED 1
ADD ./agent /
ADD ./utils /
ADD ./checkpoints /checkpoints
ADD requirements/agent_random.txt /
RUN pip install --upgrade pip
RUN pip install -r agent_random.txt

CMD [ "python", "runner.py" ]
